# Generated by Django 3.2.7 on 2021-10-07 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0002_remove_make_origin'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='nickname',
            field=models.CharField(default='any nickname', max_length=300),
            preserve_default=False,
        ),
    ]
