# Generated by Django 3.2.7 on 2021-10-07 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0003_auto_nickname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auto',
            name='area',
        ),
        migrations.RemoveField(
            model_name='auto',
            name='shape',
        ),
        migrations.RemoveField(
            model_name='auto',
            name='year',
        ),
    ]
