# Generated by Django 3.2.7 on 2021-10-07 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0004_auto_20211007_2108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auto',
            name='model',
        ),
    ]
